title: Guia para debuggear microcontrolador clon en placas de desarrollo BluePill usando STLINK
description: Guia pr√°ctica para debuggear cualquier microcontrolador ARM mediante protocolo SWD y OpenOCD.
remote_theme: just-the-docs/just-the-docs
source: .

collections:
  docs:
    permalink: "/:path/"
    output: true
